apiVersion: v1
kind: Pod
metadata:
  name: database-pod
  labels:
    app: database
spec:
  containers:
  - name: database
    image: gvenzl/oracle-xe:21-slim
    env:
    - name: ORACLE_PASSWORD
      value: "123"
    ports:
      - containerPort: 1521


# kubectl apply -f .\k8s\pod.yaml
# kubectl get pods

# kubectl logs test-pod

#Para borrar kubectl delete --all pods